name: CI

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-node-
                      ${{ runner.OS }}-
            - name: Install Packages
              run: npm ci
            - name: Validate Current Configuration (deneb-config.json)
              run: npm run validate-config-for-commit
            - name: Linting Checks
              run: npm run lint
            - name: Prettier Checks
              run: npm run prettier-check
            - name: Unit Tests
              run: npm test
            - name: Confirm pbiviz package (AppSource Version)
              run: npm run package
            - name: Alpha Channel Build Check
              if: github.ref == 'refs/heads/main'
              run: |
                  echo "alpha_build=true" >> $GITHUB_ENV
            - name: 'Alpha Channel Build'
              if: env.alpha_build == 'true'
              run: npm run package-alpha
            - name: 'Publish/Update Alpha Channel Pre-Release'
              if: env.alpha_build == 'true'
              uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'alpha'
                  prerelease: true
                  title: 'Alpha Channel: Latest Build'
                  files: |
                      dist/ALPHA*.pbiviz
    milestone-build:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: 'Check for Beta Channel Tag'
              uses: rickstaa/action-contains-tag@v1
              id: contains_beta_tag
              with:
                  reference: 'main'
                  tag: 'beta'
            - name: Beta Channel Build Check
              if: github.ref == 'refs/heads/main' && steps.contains_beta_tag.outputs.retval == 'true'
              run: |
                  echo "beta_build=true" >> $GITHUB_ENV
            - name: Checkout Project
              if: env.beta_build == 'true'
              uses: actions/checkout@v2
            - name: Setup Node
              if: env.beta_build == 'true'
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Cache Node.js modules
              if: env.beta_build == 'true'
              uses: actions/cache@v2
              with:
                  path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-node-
                      ${{ runner.OS }}-
            - name: Install Packages
              if: env.beta_build == 'true'
              run: npm ci
            - name: 'Beta Channel Build'
              if: env.beta_build == 'true'
              run: npm run package-beta
            - name: 'Publish/Update Beta Channel Pre-Release'
              if: env.beta_build == 'true'
              uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'beta'
                  prerelease: true
                  title: 'Beta Channel: Latest Build'
                  files: |
                      dist/BETA*.pbiviz
